version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: sgfood-db
    restart: always
    env_file:
      - .env
    networks:
      - spring-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: naaadang/devops-team6
    container_name: sgfood-app
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - spring-network
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  spring-network:
    driver: bridge
