version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: sgfood-db
    restart: always
    env_file:
      - .env
    networks:
      - spring-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: naaadang/devops-team6:latest
    container_name: sgfood-app
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - spring-network
    ports:
      - "8081:8081"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "5001:9090"
    networks:
      - spring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "5002:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - spring-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - spring-network
    ports:
      - "5003:8080"

volumes:
  postgres_data:
  grafana-storage:

networks:
  spring-network:
    driver: bridge
