spring:
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 50
      thread-name-prefix: "Async-"

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL에 맞는 Hibernate dialect
        format_sql: true # SQL을 보기 쉽게 출력
        jdbc :
          use_streams_for_binary: true
          lob:
            non_contextual_creation: true


logging:
  level:
    root: debug
    org:
      springframework:
      security: DEBUG
  file:
    path: logs/app.log

server:
  port: 8081 
  error:
    include-message: always
    include-stacktrace: always
    

#prometheus, grafana
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
