name: JMeter Performance Test

on:
  workflow_run:
    workflows: ["Deploy to EC2"] # 또는 "Deploy"
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Wait for application to start
        run: |
          echo "Waiting for 30 seconds for the application to stabilize..."
          sleep 30

      - name: Install, Run, and Debug JMeter
        # apt-get 대신 최신 버전을 직접 다운로드하여 설치합니다.
        # jmeter가 실패하더라도 로그 확인을 위해 다음 스텝을 계속 진행
        continue-on-error: true
        run: |
          # --- 1. JMeter 설치 (최신 버전) ---
          JMETER_VERSION=5.6.3
          JMETER_INSTALL_DIR="jmeter_install"
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xzf apache-jmeter-$JMETER_VERSION.tgz
          mv apache-jmeter-$JMETER_VERSION $JMETER_INSTALL_DIR
          echo "$PWD/$JMETER_INSTALL_DIR/bin" >> $GITHUB_PATH

          # --- 2. JMeter 테스트 실행 ---
          echo "Starting JMeter command..."
          rm -rf report
          jmeter -n \
                 -t jmeter/performance-test.jmx \
                 -Jserver.host=${{ secrets.SERVER_HOST }} \
                 -Jserver.port=443 \
                 -l result.jtl \
                 -e -o report
        
      - name: Check logs and directory state
        # 이전 스텝의 성공 여부와 관계없이 항상 이 스텝을 실행
        if: always()
        run: |
          echo "--- Current directory contents ---"
          ls -al
          
          echo
          echo "--- Checking result.jtl file ---"
          if [ -f "result.jtl" ]; then
            echo "✅ result.jtl file created. Displaying first 10 lines:"
            head -n 10 result.jtl
          else
            echo "❌ result.jtl file NOT found."
          fi

          echo
          echo "--- Displaying jmeter.log for debugging ---"
          # JMeter 로그 파일은 설치 경로의 bin 폴더 안에 생성됩니다.
          LOG_FILE="jmeter_install/bin/jmeter.log"
          if [ -f "$LOG_FILE" ]; then
            echo "✅ Displaying contents of $LOG_FILE:"
            cat "$LOG_FILE"
          else
            echo "❌ $LOG_FILE NOT found."
          fi
          
      - name: Final check for report folder
        run: |
          if [ -d "report" ]; then
            echo "✅ Report folder exists"
          else
            echo "❌ Report folder was not created. Check the logs above."
            exit 1
          fi

      - name: Upload JMeter Test Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-report
          path: report
