name: JMeter Performance Test

on:
  workflow_run:
    workflows: ["Deploy to EC2"]
    types:
      - completed
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Wait for application to start
        run: |
          echo "Waiting for 30 seconds..."
          sleep 30

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter test
        run: |
          jmeter -n \
                 -t jmeter/performance-test.jmx \
                 -Jserver.host=${{ secrets.SERVER_HOST }} \
                 -Jserver.port=443 \
                 -l result.jtl

      - name: Upload Raw Result File
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-jtl-result
          path: result.jtl
